import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

import { Suspense } from "react";
import Loading from "./loading";

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Suspense fallback={<Loading />}>{children}</Suspense>
			</body>
		</html>
	);
}
